### PR TITLE
Implemented localization

### PR DESCRIPTION
**Pull request by halvors**
This implements localization. Mostly focused on the JSON api, but also considered for other uses.

It is simply a registry that holds the localized strings. Currently i see no use for implementing other languages than nb_NO. But because i've centralized the function Localization::getLocale(), this can easily be changed at a later time.

This is currently still "Work in Progress" but submitting this PR now so that others also could have a look at it.

Work that need to be done.
- [x] Localize json/agenda
- [x] Localize json/application
- [x] Localize json/avatar
- [x] Localize json/chat
- [x] Localize json/clan
- [x] Localize json/compo
- [x] Localize json/email
- [x] Localize json/event
- [x] Localize json/group
- [x] Localize json/invite
- [x] Localize json/location
- [x] Localize json/match
- [x] Localize json/page
- [x] Localize json/pay
- [x] Localize json/permissions
- [x] Localize json/restrictedpage
- [x] Localize json/row
- [x] Localize json/seatmap
- [x] Localize json/session
- [x] Localize json/slide
- [x] Localize json/team
- [x] Localize json/ticket
- [x] Localize json/user

### CODE REVIEW

**Comment by halvors** [comment]
@petterroea Looks good?

**Comment by petterroea** [comment]
I don't see why we should focus on localisation on a norwegian local lan party, but eh, i like the implementation. Go for it if you are happy with it.

A suggestion would be to have localisation in a json file.

**Comment by halvors** [comment]
@petterroea The idea is not localization, but more standardization of common strings. But it's designed kinda like a localization system, in lack of a better name, and it can be used for localization in the future.

**Comment by petterroea** [comment]
Yeah, i like it.

What do you think about localizing in a seperate json file though? We could have a system of a "fallback language" (norwegian) for not-supported strings, and the ability to add multiple languages

**Comment by halvors** [comment]
We can look into that in the future, but we'll still reference the same way as this right? 

So basically make Localization read from a json file then, everything else works as before?

**Comment by petterroea** [comment]
ye, sounds good

**Comment by halvors** [comment]
@petterroea Simple json translation files is now implemented.

**Pull request merged**
